### ISSUE TITLE
Build com.lge.ivi.jar 

### ISSUE THREAD

**Issue by ayasystems** [g4rb4g3/ivireceiver#2]
Could you help me with these steps?

> Then you have to deodex it.
> Next you have to convert it back to java (dex2jar is your friend).

I've extracted com.lge.ivi.jar & com.lge.ivi.odex from my NAV (ioniq phev 2019)
I want to try to adjust your app to PHEV units. 

Regards!

**Comment by g4rb4g3** [comment]
Check this, that should answer all your questions.

https://www.xda-developers.com/deodex-all-the-things-with-universal-deodexer/

https://github.com/pxb1988/dex2jar

**Comment by ayasystems** [comment]
Thanks a lot! i have it working!

I'm ussing an obd2 bluetooth modified with an ESP8266 with esplink firmware. 

I have a 4g router on my ioniq. Torque has access to OBD2 without problem.... 

Starting from you code i will try to add obd2 information on your dashboard....

I will publish the code when it cames ready
